#!/bin/bash -x
script_file=`readlink -f "$0"`
script_dir=`dirname "$script_file"`

input_script=`readlink -f "$1"`
input_dir=`dirname "$input_script"`
script_name=`basename "$input_script"`
shift

docker run --rm -it -v "$input_dir:/script/:rw" rothan/arsoft-python:latest python "/script/$script_name" $@
