#!/usr/bin/python
import os,sys

from arsoft.nagios import NagiosPlugin, OK, WARNING, CRITICAL, UNKNOWN
from arsoft.fritzbox import *

## Create the plugin option
np = NagiosPlugin(must_threshold=False)
np.add_value('down', 'defines the range for the down stream speed', guitext='down stream', units='bit/s', warning=True)
np.add_value('up', 'defines the range for the up stream speed', guitext='up stream', units='bit/s', warning=True)

## This starts the actual plugin activation
np.activate()

## Use a custom load average file, if specified to
## This is really only used for debugging purposes, and showing off the
## 'add_arg' method
if np['host']:
    target_host = np['host']
else:
    target_host = 'fritz.box'

fritz = FritzBox(target_host)

if fritz.isPhysicalConnected():

    if fritz.isDSLConnected():
        downStream = fritz.physicalLinkDownStream()
        upStream = fritz.physicalLinkUpStream()

        ## set the values
        np.set_value('down', downStream)
        np.set_value('up', upStream)
        
        (exit_code, exit_message) = np.check_values()
        
        if exit_code == OK:
            exit_message = 'connected since %s with %s' % (str(fritz.connectTime()), str(fritz.wanAddress()))
        
        np.nagios_exit(exit_code, exit_message)
    else:
        np.nagios_exit("CRITICAL", 'DSL link is not up! (%s)' % str(fritz.dslLinkStatus()))
else:
    np.nagios_exit("CRITICAL", 'Physical link is not up! (%s)' % str(fritz.physicalLinkStatus()))
