#!/usr/bin/python3
import os,sys
from datetime import datetime, timedelta
import time

from arsoft.nagios import NagiosPlugin, OK, WARNING, CRITICAL, UNKNOWN
from arsoft.utils import runcmdAndGetData
import yaml

## Create the plugin option
np = NagiosPlugin(must_threshold=False)
np.add_arg('w', 'warning', 'warning threshold in seconds', default=3600, required=0)
np.add_arg('c', 'critical', 'critical threshold in seconds', default=7200, required=0)
np.add_arg('s', 'statefile', 'name of puppet agent state file', default='/var/lib/puppet/state/last_run_summary.yaml', required=0)
np.add_arg('p', 'pidfile', 'name of puppet agent state file', default='/var/run/puppet/agent.pid', required=0)
np.add_arg('m', 'minversion', 'specifies the minimum version.', default='3.0.0', required=0)
np.add_arg('r', 'running', 'if not specified checks if agent is running; if set to zero checks if agent is stopped.', default=1, required=0)

## This starts the actual plugin activation
np.activate()

np.add_value('time_since_last', 'time since last puppet run', 'time since last run', uom='s', has_argument=False, value=0)
np.add_value('config', 'timestamp of the applied catalog', 'catalog version', has_argument=False, value=0)
np.add_value('skipped', 'number of skipped resources', 'skipped', has_argument=False, value=0)
np.add_value('restarted', 'number of restarted resources', 'restarted', has_argument=False, value=0)
np.add_value('changed', 'number of changed resources', 'changed', has_argument=False, value=0)
np.add_value('failed', 'number of failed resources', 'failed', has_argument=False, value=0)
np.add_value('failed_to_restart', 'number of resources which failed to restart', 'failed to restart', has_argument=False, value=0)
np.add_value('out_of_sync', 'number of resources which are out of sync', 'out-of-sync', has_argument=False, value=0)
np.add_value('total', 'total number of resources', 'total', has_argument=False, value=0)

running = True if int(np['running']) != 0 else False

def version_str_to_num(s):
    (major, minor, patch) = s.split('.')
    try:
        ret = (int(major) * 10000) + (int(minor) * 100) + int(patch)
    except ValueError:
        ret = 0
    return ret

try:
    f = open(np['pidfile'], 'r')
    pid = int(f.read())
    f.close()
except IOError:
    pid = None
except ValueError:
    pid = None

if pid:
    try:
        pgid = os.getpgid(pid)
        puppet_running = True if pgid > 0 else False
    except:
        puppet_running = False
else:
    puppet_running = False

if running:
    if not puppet_running:
        exit_code = CRITICAL
        exit_message = 'Puppet agent not running'
    else:
        (sts, stdoutdata, stderrdata) = runcmdAndGetData('/usr/bin/puppet', ['--version'], env={'HOME':'/tmp', 'LANG':'C'})
        if sts == 0:
            puppet_version_str = stdoutdata.strip()
            puppet_version = version_str_to_num(puppet_version_str)
            minversion = version_str_to_num(np['minversion'])

            if puppet_version > minversion:
                (sts, stdoutdata, stderrdata) = runcmdAndGetData('/usr/bin/sudo', ['/bin/cat', np['statefile'] ])
                if sts == 0:
                    now = time.time()
                    last_run_summary = yaml.load(stdoutdata)
                    last_run = last_run_summary['time']['last_run']
                    time_since_last = now - last_run
                    num_failed = 0
                    num_failed_to_restart = 0
                    num_changed = 0
                    num_skipped = 0
                    num_restarted = 0
                    num_out_of_sync = 0
                    num_total = 0

                    np.set_value('config', last_run_summary['version']['config'])
                    np.set_value('time_since_last', int(time_since_last))
                    if 'resources' in last_run_summary:
                        num_failed = int(last_run_summary['resources']['failed'])
                        num_failed_to_restart = int(last_run_summary['resources']['failed_to_restart'])
                        num_changed = int(last_run_summary['resources']['changed'])
                        num_skipped = int(last_run_summary['resources']['skipped'])
                        num_restarted = int(last_run_summary['resources']['restarted'])
                        num_out_of_sync = int(last_run_summary['resources']['out_of_sync'])
                        num_total = int(last_run_summary['resources']['total'])
                        np.set_value('skipped', num_skipped)
                        np.set_value('restarted', num_restarted)
                        np.set_value('changed', num_changed)
                        np.set_value('failed', num_failed)
                        np.set_value('failed_to_restart', num_failed_to_restart)
                        np.set_value('out_of_sync', num_out_of_sync)
                        np.set_value('total', num_total)

                    #print('num_changed=%i' % num_changed)
                    #print('crit=%i' % int(np['critical']))
                    #print('warn=%i' % int(np['warning']))
                    if int(time_since_last) > int(np['critical']):
                        exit_code = CRITICAL
                        exit_message = 'Puppet out-of-date; last update at %s, %s ago' % (datetime.fromtimestamp(last_run), timedelta(seconds=int(time_since_last)))
                    elif int(time_since_last) > int(np['warning']):
                        exit_code = WARNING
                        exit_message = 'Puppet out-of-date; last update at %s, %s ago' % (datetime.fromtimestamp(last_run), timedelta(seconds=int(time_since_last)))
                    else:
                        if num_failed > 0:
                            exit_code = WARNING
                            exit_message = 'Puppet agent failed with %i resources' % (num_failed)
                        elif num_failed_to_restart > 0:
                            exit_code = WARNING
                            exit_message = 'Puppet agent failed to restart %i services' % (num_failed_to_restart)
                        else:
                            exit_code = OK
                            exit_message = 'Puppet agent running %i resources changed' % (num_changed)
                else:
                    exit_code = CRITICAL
                    exit_message = 'Failed to read ' + str(np['statefile']) + '; error ' + str(stderrdata)
            else:
                exit_code = CRITICAL
                exit_message = 'Puppet version ' + puppet_version_str + ' < ' + str(np['minversion'])
        else:
            exit_code = CRITICAL
            exit_message = 'Failed to retrieve puppet version; error ' + str(stderrdata)
else:
    if not puppet_running:
        exit_code = OK
        exit_message = 'Puppet agent not running'
    else:
        exit_code = CRITICAL
        exit_message = 'Puppet agent is running, but should not be running'

np.nagios_exit(exit_code, exit_message)
