#!/usr/bin/python
import os,sys

from arsoft.nagios import NagiosPlugin, OK, WARNING, CRITICAL, UNKNOWN
from arsoft.fritzbox import *

## Create the plugin option
np = NagiosPlugin(must_threshold=False)
np.add_value('down', 'defines the range for the down stream speed', guitext='down stream', uom='KB', warning=True)
np.add_value('up', 'defines the range for the up stream speed', guitext='up stream', uom='KB', warning=True)

## This starts the actual plugin activation
np.activate()

## Use a custom load average file, if specified to
## This is really only used for debugging purposes, and showing off the
## 'add_arg' method
if np['host']:
    target_host = np['host']
else:
    np.nagios_exit(UNKNOWN, 'No hostname for FritzBox specified.')

fritz = FritzBox(target_host)

if fritz.isPhysicalConnected():

    if fritz.isDSLConnected():
        downStream_in_bits = fritz.physicalLinkDownStream()
        upStream_in_bits = fritz.physicalLinkUpStream()
        
        downStream_in_kb = downStream_in_bits / 8 / 1024
        upStream_in_kb = upStream_in_bits / 8 / 1024

        ## set the values
        np.set_value('down', downStream_in_kb)
        np.set_value('up', upStream_in_kb)
        
        (exit_code, exit_message) = np.check_values()
        
        if exit_code == OK:
            exit_message = 'connected since %s with %s' % (str(fritz.connectTime()), str(fritz.wanAddress()))
        
        np.nagios_exit(exit_code, exit_message)
    else:
        np.nagios_exit(CRITICAL, 'DSL link is not up! (%s)' % str(fritz.dslLinkStatus()))
else:
    np.nagios_exit(CRITICAL, 'Physical link is not up! (%s)' % str(fritz.physicalLinkStatus()))
