#!/bin/bash

root_device_partition='/dev/sda1'
export ACTION=add
req_env=`udevadm info -n $root_device_partition | awk '/E:/ { print $2}'`

for e in $req_env; do
	export $e
done

this_script=`readlink -f $0`
this_dir=`dirname "$this_script"`
"$this_dir/edskmgr" --verbose --udev-partition --hook-dir "$this_dir/edskmgr-support/hooks"


