#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

import sys
import os
import argparse
from arsoft.disks.edskmgr import ExternalDiskManager
from arsoft.disks.disk import Disk, Disks

class ExternalDiskManagerApp(object):

    def __init__(self):
        self._mgr = ExternalDiskManager()

    def show_status(self):
        print('Internal disks:')
        for disk in self._mgr.internal_disks:
            print('  ' + disk)
        print('External disks:')
        for disk in self._mgr.external_disks:
            print('  ' + disk)

        e = Disks()
        print('Available disks:')
        for disk_obj in e.disks:
            print('  ' + '%s %s (%s)'%(str(disk_obj.vendor), str(disk_obj.model), str(disk_obj.serial)))
            if self._mgr.verbose:
                print('    Native path: %s'%(disk_obj.nativepath))
            print('    Path:        %s'%(disk_obj.path))
            print('    Removeable:  %s'%('yes' if disk_obj.is_removable else 'no'))
            print('    System:      %s'%('yes' if disk_obj.is_system_disk else 'no'))
            print('    Internal:    %s'%('yes' if self._mgr.is_internal_disk(disk_obj) else 'no'))

    def main(self, argv=None):
        #=============================================================================================
        # process command line
        #=============================================================================================
        parser = argparse.ArgumentParser(description='manages external hard disks.')
        parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='enable verbose output of this script.')
        parser.add_argument('-C', '--config-directory', dest='configdir', default=self._mgr.config_dir, help='name of the directory containing the external disk manager configuration.')
        parser.add_argument('--noop', dest='noop', action='store_true', help='just tests and shows what would be done.')
        parser.add_argument('--load', dest='load', action='store_true', help='rescans all empty host interfaces.')
        parser.add_argument('--reset-config', dest='reset_config', action='store_true', help='reset configuration and treat all disks as internal ones.')
        parser.add_argument('--eject', dest='eject', nargs='*', help='removes the given external disks or all present external disks.')
        parser.add_argument('--udev-disk', dest='udev_disk', action='store_true', help='handles disk event within udev.')
        parser.add_argument('--udev-partition', dest='udev_partition', action='store_true', help='handles partition event within udev.')
        parser.add_argument('--trigger', dest='trigger', help='specifies the name of the action; use by other scripts.')
        parser.add_argument('--register', dest='register', nargs='+', metavar='DISK', help='registers the given disk as external HDD to the system.')
        parser.add_argument('--unregister', dest='unregister', nargs='+', metavar='DISK', help='unregisters the given disk from the known external HDDs of the system.')
        parser.add_argument('--tag', dest='tags', action='append', help='sets the tags for the disk to register.')
        parser.add_argument('--status', dest='status', action='store_true', help='shows the status of all external disks.')

        args = parser.parse_args()

        self._mgr.verbose = args.verbose
        self._mgr.noop = args.noop
        self._mgr.trigger = args.trigger

        self._mgr.load_config(args.configdir)

        if args.reset_config:
            if self._mgr.reset_config():
                if not self._mgr.write_config():
                    sys.stderr.write('Failed to write config')
                    ret = 2
                else:
                    ret = 0
            else:
                ret = 1
        elif args.load:
            if self._mgr.checkRoot():
                if not self._mgr.rescan_empty_scsi_hosts():
                    ret = 1
                else:
                    ret = 0
            else:
                ret = 1
        elif args.eject is not None:
            if self._mgr.checkRoot():
                if len(args.eject) == 0:
                    if not self._mgr.remove_external_disks():
                        ret = 1
                    else:
                        ret = 0
                else:
                    if not self._mgr.remove_disks(args.eject):
                        ret = 1
                    else:
                        ret = 0
            else:
                ret = 1
        elif args.udev_disk or args.udev_partition:
            if self._mgr.checkRoot():
                if not self._mgr.udev_action():
                    ret = 1
                else:
                    ret = 0
            else:
                ret = 1
        elif args.register is not None:
            if self._mgr.register_disk(args.register, external=True, tags=args.tags):
                self._mgr.write_config()
                ret = 0
            else:
                ret = 1
        elif args.unregister is not None:
            # do not really unregister the whole disk, just register it as
            # internal and remove all tags
            if self._mgr.register_disk(args.unregister, external=False, tags=[]):
                self._mgr.write_config()
                ret = 0
            else:
                ret = 1
        elif args.status:
            ret = self.show_status()
        else:
            sys.stderr.write("no operation specified.\n")
            ret = 1
        self._mgr.cleanup()
        return ret


if __name__ == "__main__":
    app = ExternalDiskManagerApp()
    sys.exit(app.main(sys.argv))
