#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

import sys
import os
import argparse
from arsoft.hostsfile import HostsFile

class ManageHostsApp(object):
    
    def __init__(self):
        self.verbose = False
        self.quiet = False
        self.hostsfile = HostsFile()
    
    def main(self):
        #=============================================================================================
        # process command line
        #=============================================================================================
        parser = argparse.ArgumentParser(description='manages the local hosts entry file')
        parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='enable verbose output.')
        parser.add_argument('--update', dest='update', nargs=2, help='update the specified host entry.')
        parser.add_argument('--list', dest='list', action='store_true', help='lists all host entries.')

        args = parser.parse_args()
        self.verbose = args.verbose
        
        ret = 0
        if args.update:
            update_key = args.update[0]
            update_values = args.update[1].split(',')
            self.hostsfile[update_key] = update_values
        elif args.list:
            for (address, hostnames) in self.hostsfile:
                print('%s\t%s' % (address, ','.join(hostnames)))
        else:
            sys.stderr.write('No operation specified.\n')
        return ret

if __name__ == "__main__":
    app = ManageHostsApp()
    sys.exit(app.main())
