#!/bin/bash
NSSWITCH_CONF='/etc/nsswitch.conf'
verbose=0
action=''

nsswitch_ldap_modify() {
	local enable="$1"
	if [ $enable -eq 0 ]; then
		/usr/sbin/nsswitch-config \
			--set passwd files \
			--set group files \
			--set shadow files \
			--set aliases files \
			--set automount files \
			--set sudoers files
		RES=$?
	else
		/usr/sbin/nsswitch-config \
			--set passwd files ldap \
			--set group files ldap \
			--set shadow files ldap \
			--set aliases files ldap \
			--set automount ldap \
			--set sudoers files ldap
		RES=$?
	fi
	if [ $RES -ne 0 ]; then
		echo "Failed to modify $NSSWITCH_CONF" 1>&2
	fi
}

function usage()
{
	echo "nsswitch-ldap [OPTIONS] <enable|disable>"
	echo "    -h, --help      shows this help screen"
	echo "    -v,--verbose    verbose output"
	echo "    enable          enables the nss-ldap lookup"
	echo "    disable         disables the nss-ldap lookup"
	exit 0
}

# parse command line arguments
while [ $# -ne 0 ]; do
	case "$1" in
		"-?"|"-h"|"--help") usage;;
		"enable"|"disable") action="$1"; ;;
		*)
			echo "Unknown parameter $1" 1>&2
			exit 1
		;;
	esac
	shift
done

if [ -z "$action" ]; then
	echo "Neither 'enable' nor 'disable' is specified.'" 1>&2
	exit 1
else
	case "$action" in
		'enable') nsswitch_ldap_modify 1; ;;
		'disable') nsswitch_ldap_modify 0; ;;
	esac
fi
