#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

import urllib2
import json
import os
import errno
import sys
from arsoft.inifile import IniFile
from arsoft.check_mk import *

class puppetdb_check_mk_plugin(object):

    JETTY_INI = '/etc/puppetlabs/puppetdb/conf.d/jetty.ini'
    SERVICE_NAME = 'puppetdb'
    SYSTEMCTL = '/bin/systemctl'

    def __init__(self):
        self._hostname = 'localhost'
        self._port = 0
        self._sslport = 0
        self._https = False
        self._version = ''
        self._pid = 0
        self._running = False
        self._beans = {}

        self._get_config()

        if self._port:
            self._pid, self._running = systemd_status(self.SERVICE_NAME)
            self._beans['memory'] = '/metrics/v1/mbeans/java.lang:type=Memory'
            self._beans['threading'] = '/metrics/v1/mbeans/java.lang:type=Threading'
            
            self._beans['catalogs_dups']  = '/metrics/v1/mbeans/puppetlabs.puppetdb.scf.storage:type=default,name=duplicate-pct'
            self._beans['resources_dups'] = '/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=pct-resource-dupes'
            self._beans['num_resources']  = '/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-resources'
            self._beans['num_nodes']      = '/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-nodes'
            
            self._beans['avg_resources_per_node'] = '/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=avg-resources-per-node'
            
            self._beans['db'] = '/metrics/v1/mbeans/com.jolbox.bonecp:type=BoneCP'
            self._beans['mq'] = '/metrics/v1/mbeans/org.apache.activemq:type=Broker,brokerName=localhost,destinationType=Queue,destinationName=puppetlabs.puppetdb.commands'
            
            self._beans['version'] = '/pdb/meta/v1/version'

    def _get_config(self):
        if os.path.isfile(self.JETTY_INI):
            inifile = IniFile(commentPrefix='#', keyValueSeperator='=', disabled_values=False)
            if inifile.open(self.JETTY_INI):
                try:
                    self._port = int(inifile.get('jetty', 'port', 8080))
                    self._sslport = int(inifile.get('jetty', 'ssl-port', 8081))
                except ValueError:
                    pass

    def _get_bean(self, bean):
        url = 'http%s://%s:%d%s' % ('s' if self._https else '', self._hostname, self._port, bean)
        headers = { 'Accept': 'application/json' }
        #print(url)
        ret = None
        req = urllib2.Request(url, None, headers)
        try:
            response = urllib2.urlopen(req)
            ret = json.loads(response.read())
        except urllib2.URLError:
            pass
        return ret

    def status(self):
        if self._port or self._sslport:
            print('port;%i' % self._port)
            print('sslport;%i' % self._sslport)
            print('pid;%i' % self._pid)
            print('running;%i' % self._running)
            for bean in self._beans:
                v = self._get_bean(self._beans[bean])
                if v:
                    if isinstance(v, dict):
                        if len(v) == 1:
                            value = v.values()[0]
                            print('%s;%s' % (bean, value))
                        else:
                            for (key, value) in v.iteritems():
                                if isinstance(value, dict):
                                    for (value_key, value_value) in value.iteritems():
                                        print('%s_%s_%s;%s' % (bean, key.lower(), value_key.lower(), value_value))
                                else:
                                    print('%s_%s;%s' % (bean, key.lower(), value))
        return 0

if __name__ == "__main__":
    print("<<<puppetdb:sep(59)>>>")
    pl = puppetdb_check_mk_plugin()
    sys.exit(pl.status())
