#!/usr/bin/python
import os,sys
import re
import datetime

LINE_PATTERN = r'^\[\s*(?P<timestamp>[0-9]{2}\:[0-9]{2}\:[0-9]{2})\]\s((?P<loglevel>[A-Z][a-z]+)\:\s+)?(?P<message>.*)$'
START_END_DATE_PATTERN = r'^(Start|End) date is (?P<timestamp>.*)$'

logfile = '/var/log/rkhunter.log'
line_re = re.compile(LINE_PATTERN)
start_end_date_re = re.compile(START_END_DATE_PATTERN)

def _parse_timestamp(timestamp, ref_timestamp):
    ret = datetime.datetime.strptime(timestamp, '%H:%M:%S')
    if ret:
        if not ref_timestamp:
            ref_timestamp = datetime.datetime.now()
        ret = ret.replace(year=ref_timestamp.year, month=ref_timestamp.month, day=ref_timestamp.day)
    return ret

class MessageObject(object):
    def __init__(self, timestamp=None, loglevel=None, message=None):
        self.timestamp = timestamp
        if loglevel is not None:
            self.loglevel = loglevel.upper()
        else:
            self.loglevel = None
        self.message = message

class rkhunter_mk_check_plugin(object):
    def __init__(self, logfile='/var/log/rkhunter.log'):
        self.start_date = None
        self.end_date = None
        self.num_infects = 0
        self.num_criticals = 0
        self.num_errors = 0
        self.num_warnings = 0
        self.num_infos = 0
        self.num_file_properties_changed = 0
        self.changed_file_properties = []
        self.num_services_changed = 0
        self.changed_services = []
        self.num_users_changed = 0
        self.changed_users = []
        self.num_groups_changed = 0
        self.changed_groups = []
        self.num_downloads_failed  = 0
        self.downloads_failed = []
        self.warnings = []
        self.errors = []
        self.criticals = []
        self.infects = []
        self.current_message = None
        self.check_time = 0
        self.check_age = 0

        self._process(logfile)

    def _process_message(self, msgobj):
        if msgobj.loglevel == 'WARNING':
            if 'The file properties have changed:' in msgobj.message:
                self.num_file_properties_changed += 1
                f_start = msgobj.message.find('File:')
                if f_start > 0:
                    f_start += 6
                    f_end = msgobj.message.find('\n', f_start)
                    f_name = msgobj.message[f_start:f_end] if f_end > 0 else msgobj.message[f_start:]
                    self.changed_file_properties.append(f_name)
            elif 'Found enabled xinetd service:' in msgobj.message:
                self.num_services_changed += 1
                f_start = msgobj.message.find('service:')
                if f_start > 0:
                    f_start += 9
                    f_end = msgobj.message.find('\n', f_start)
                    f_name = msgobj.message[f_start:f_end] if f_end > 0 else msgobj.message[f_start:]
                    self.changed_services.append(f_name)
            elif msgobj.message.startswith('User '):
                self.num_users_changed += 1
                f_start = msgobj.message.find('\'')
                if f_start > 0:
                    f_start += 1
                    f_end = msgobj.message.find('\'', f_start)
                    f_name = msgobj.message[f_start:f_end] if f_end > 0 else msgobj.message[f_start:]
                    self.changed_users.append(f_name)
            elif msgobj.message.startswith('Group '):
                self.num_groups_changed += 1
                f_start = msgobj.message.find('\'')
                if f_start > 0:
                    f_start += 1
                    f_end = msgobj.message.find('\'', f_start)
                    f_name = msgobj.message[f_start:f_end] if f_end > 0 else msgobj.message[f_start:]
                    self.changed_groups.append(f_name)
            elif msgobj.message.startswith('Download of '):
                self.num_downloads_failed += 1
                f_start = msgobj.message.find('\'')
                if f_start > 0:
                    f_start += 1
                    f_end = msgobj.message.find('\'', f_start)
                    f_name = msgobj.message[f_start:f_end] if f_end > 0 else msgobj.message[f_start:]
                    self.downloads_failed.append(f_name)
            else:
                self.num_warnings += 1
                self.warnigns.append(msgobj.message)
        elif msgobj.loglevel == 'ERROR':
            self.num_errors += 1
            self.errors.append(msgobj.message)
        elif msgobj.loglevel == 'CRITICAL':
            self.num_criticals += 1
            self.criticals.append(msgobj.message)
        elif msgobj.loglevel == 'INFO':
            self.num_infos += 1

    def _process(self, logfile):
        try:
            f = open(logfile, 'r')
            for line in f:
                mo = line_re.match(line)
                if mo:
                    mogrp = mo.groupdict()
                    message_text = mo.group('message')
                    loglevel = mo.group('loglevel') if 'loglevel' in mogrp else None

                    if self.start_date is None:
                        modate = start_end_date_re.match(message_text)
                        if modate:
                            self.start_date = datetime.datetime.strptime(modate.group('timestamp'), "%a %b %d %H:%M:%S %Z %Y")
                    elif self.end_date is None:
                        modate = start_end_date_re.match(message_text)
                        if modate:
                            self.end_date = datetime.datetime.strptime(modate.group('timestamp'), "%a %b %d %H:%M:%S %Z %Y")

                    timestamp = _parse_timestamp(mo.group('timestamp'), self.start_date)

                    if loglevel is None:
                        if self.current_message is not None:
                            self.current_message.message += '\n' + message_text
                    else:
                        if self.current_message is not None:
                            self._process_message(self.current_message)
                        self.current_message = MessageObject(timestamp, loglevel, message_text)
            f.close()
            if self.current_message is not None:
                self._process_message(self.current_message)

        except IOError as e:
            pass

        if self.start_date is not None and self.end_date is not None:
            now = datetime.datetime.now()
            self.check_time = (self.end_date - self.start_date).total_seconds()
            self.check_age = (now - self.end_date).total_seconds()

    def output(self):
        print('check_time;%i' % self.check_time)
        print('check_age;%i' % self.check_age)
        print('num_infects;%i' % self.num_infects)
        print('infects;%s' % ','.join(self.infects))
        print('num_criticals;%i' % self.num_criticals)
        print('criticals;%s' % ','.join(self.criticals))
        print('num_errors;%i' % self.num_errors)
        print('errors;%s' % ','.join(self.errors))
        print('num_warnings;%i' % self.num_warnings)
        print('warnings;%s' % ','.join(self.warnings))
        print('num_infos;%i' % self.num_infos)
        print('num_file_properties_changed;%i' % self.num_file_properties_changed)
        print('changed_file_properties;%s' % ','.join(self.changed_file_properties))
        print('num_services_changed;%i' % self.num_services_changed)
        print('changed_services;%s' % ','.join(self.changed_services))
        print('num_users_changed;%i' % self.num_users_changed)
        print('changed_users;%s' % ','.join(self.changed_users))
        print('num_groups_changed;%i' % self.num_groups_changed)
        print('changed_groups;%s' % ','.join(self.changed_groups))
        print('num_downloads_failed;%i' % self.num_downloads_failed)
        print('downloads_failed;%s' % ','.join(self.downloads_failed))

if __name__ == "__main__":
    print("<<<rkhunter:sep(59)>>>")
    pl = rkhunter_mk_check_plugin()
    pl.output()



