#!/bin/bash
verbose=0
action=''

nsswitch_winbind_modify() {
	local enable="$1"
	if [ $enable -eq 0 ]; then
		/usr/bin/nsswitch-config \
			--set passwd files \
			--set group files \
			--set shadow files
		RES=$?
	else
		/usr/bin/nsswitch-config \
			--set passwd files winbind \
			--set group files winbind \
			--set shadow files
		RES=$?
	fi
	if [ $RES -ne 0 ]; then
		echo "Failed to modify nsswitch.conf" 1>&2
	fi
}

function usage()
{
	echo "nsswitch-winbind [OPTIONS] <enable|disable>"
	echo "    -h, --help      shows this help screen"
	echo "    -v,--verbose    verbose output"
	echo "    enable          enables the nss-winbind lookup"
	echo "    disable         disables the nss-winbind lookup"
	exit 0
}

# parse command line arguments
while [ $# -ne 0 ]; do
	case "$1" in
		"-?"|"-h"|"--help") usage;;
		"enable"|"disable") action="$1"; ;;
		*)
			echo "Unknown parameter $1" 1>&2
			exit 1
		;;
	esac
	shift
done

if [ -z "$action" ]; then
	echo "Neither 'enable' nor 'disable' is specified.'" 1>&2
	exit 1
else
	case "$action" in
		'enable') nsswitch_winbind_modify 1; ;;
		'disable') nsswitch_winbind_modify 0; ;;
	esac
fi
