#!/bin/sh -e
PKG=arsoft-check-mk-checks

test ! -d /usr/share/check_mk/checks.distrib && mkdir -p /usr/share/check_mk/checks.distrib || true
dpkg-divert --add --package ${PKG} --rename \
            --divert /usr/share/check_mk/checks.distrib/apt /usr/share/check_mk/checks/apt
dpkg-divert --add --package ${PKG} --rename \
            --divert /usr/share/check_mk/special/agent_fritzbox.distrib /usr/share/check_mk/special/agent_fritzbox

#DEBHELPER#

exit 0
