#!/bin/sh -e
PKG=arsoft-check-mk-checks

if [ "$1" = remove ] ; then
    test ! -d /usr/share/check_mk/checks.distrib && mkdir /usr/share/check_mk/checks.distrib || true
	[ -f /usr/share/check_mk/checks/apt ] && rm /usr/share/check_mk/checks/apt
	dpkg-divert --remove --package ${PKG} --rename \
				--divert /usr/share/check_mk/checks.distrib/apt /usr/share/check_mk/checks/apt
fi

#DEBHELPER#

exit 0
