#!/usr/bin/python

import os

EDSKMGR_TRIGGER=None
DEVTYPE=None
if 'DEVTYPE' in os.environ:
    DEVTYPE=os.environ['DEVTYPE']
if 'EDSKMGR_TRIGGER' in os.environ:
    EDSKMGR_TRIGGER=os.environ['EDSKMGR_TRIGGER']

if DEVTYPE == 'partition' and EDSKMGR_TRIGGER == 'arsoft-backup':
    import sys
    from arsoft.disks.edskmgr import ExternalDiskManager

    edskmgr = ExternalDiskManager()
    edskmgr.load_config()
    (disk_obj, dev_obj, disk_tags) = edskmgr.udev_hook_initialize()
    if disk_obj and dev_obj:
        if 'arsoft-backup' in disk_tags:
            if not dev_obj.is_mounted:
                print('Mount partition of backup disk %s' % (dev_obj))
                dev_obj.mount()
    
