#!/bin/sh -e

case "$DEVTYPE" in
	"partition")
		/usr/bin/edskmgr --udev-partition $@
		;;
	"disk")
		/usr/bin/edskmgr --udev-disk $@
		;;
	*)
		echo "$0: unhandled device type $DEVTYPE"
		false
		;;
esac
