#!/usr/bin/python3
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

import sys
import argparse

from arsoft.efi import *

class efiinfo(object):
    def __init__(self):
        self.m_verbose = False
 

    def main(self):
        #=============================================================================================
        # process command line
        #=============================================================================================
        parser = argparse.ArgumentParser(description='shows information from EFI environment')
        parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='enable verbose output.')
        parser.add_argument('--available', dest='available', action='store_true', help='checks if EFI is available on this machine.')
        parser.add_argument('--vars', dest='vars', action='store_true', help='outputs all EFI variables.')
        parser.add_argument('--values', dest='show_values', action='store_true', help='show the EFI variable values.')

        args = parser.parse_args()

        self.m_verbose = args.verbose
        
        vars = EfiVariables.get_instance()
        if vars is None:
            sys.stderr.write('Your system is not supported.\n')
            ret = 1
        else:
            ret = 0
            if args.vars:
                for k in vars:
                    if args.show_values:
                        v = vars[k]
                        
                        try:
                            if v:
                                v = v.decode('utf8')
                        except UnicodeDecodeError:
                            v = None
                        print('%s:%s' % (k,v))
                    else:
                        print(k)

            if args.available:
                ret = 0 if vars.available() else 1

        return ret

if __name__ == "__main__":
    app =  efiinfo()
    sys.exit(app.main())
