#!/usr/bin/python3
import sys
from arsoft.sshutils import *

def ssh_with_env():
    url = SSHUrl(sys.argv[1])
    cxn = SSHConnection(url, verbose=True)
    cxn.runcmdAndGetData(['env'], outputStdErr=True, outputStdOut=True, env={'MYNAME':'rabbit'})

def ssh_script_with_env():
    url = SSHUrl(sys.argv[1])
    cxn = SSHConnection(url, verbose=True)
    cxn.runcmdAndGetData(script='env', outputStdErr=True, outputStdOut=True, env={'MYNAME':'rabbit'})

def ssh_sudo():
    url = SSHUrl(sys.argv[1])
    cxn = SSHConnection(url, verbose=True)
    key = SSHSessionKey(cxn)
    sudo = SSHSudoSession(cxn, sudo_password=sys.argv[2])
    sudo.start()
    cxn.runcmdAndGetData(['id'], sudo=True, outputStdErr=True, outputStdOut=True)

def local_sudo():
    cxn = LocalConnection(verbose=True)
    sudo = LocalSudoSession(cxn, sudo_password=sys.argv[2])
    cxn.runcmdAndGetData(['/usr/bin/id'], sudo=True, outputStdErr=True, outputStdOut=True)

def local_screen():
    cxn = LocalConnection(verbose=True)
    scr = ScreenSession(cxn)
    scr.logfile('/tmp/local_screen')
    scr.log(True)
    scr.echo('start')
    scr.runcmdAndGetData(['/usr/bin/env'], useTerminal=True, outputStdErr=True, outputStdOut=True)
    scr.echo('end')

if __name__ == "__main__":
    #local_sudo()
    #ssh_sudo()
    local_screen()
