#!/usr/bin/python3
import sys
from arsoft.sshutils import *

if __name__ == "__main__":
    url = SSHUrl(sys.argv[1])
    cxn = SSHConnection(url, verbose=True)
    key = SSHSessionKey(cxn)
    sudo = SSHSudoSession(cxn, sudo_password=sys.argv[2])
    sudo.start()
    cxn.runcmdAndGetData(sudo.command_prefix + 'id', outputStdErr=True, outputStdOut=True)

