#!/bin/sh
test ! -x /bin/networkctl && exit 0
echo "<<<networkd:sep(0)>>>"
/bin/systemctl --no-pager --lines=0 status systemd-networkd
echo "--------"
/bin/networkctl --no-pager --no-legend list
echo "<<<networkd_links:sep(0)>>>"
/bin/networkctl --no-pager --no-legend --all status
