#!/usr/bin/python
# postfix certificates
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

from arsoft.crypto.utils import check_mk_cert_file_info, check_mk_crl_file_info
from arsoft.utils import runcmdAndGetData
import sys

class postfix_cert_mk_check_plugin(object):
    def status(self):
        keys = ['smtpd_tls_cert_file', 'smtp_tls_cert_file', 'lmtp_tls_cert_file']
        args = ['/usr/sbin/postconf', '-h'] + keys
        (sts, stdoutdata, stderrdata) = runcmdAndGetData(args)
        if sts == 0:
            for line in stdoutdata.splitlines():
                if not line:
                    continue
                check_mk_cert_file_info(line)
        return 0

if __name__ == "__main__":
    print("<<<postfix_cert:sep(59)>>>")
    pl = postfix_cert_mk_check_plugin()
    sys.exit(pl.status())
