#!/bin/sh
test ! -x /bin/systemctl && exit 0
echo "<<<systemd:sep(32)>>>"
/bin/systemctl --version
echo "<<<systemd_failed>>>"
/bin/systemctl --failed --no-pager --no-legend
echo "<<<systemd_timedate:sep(0)>>>"
/usr/bin/timedatectl --no-pager status
echo "--------"
/bin/systemctl --no-pager --lines=0 status systemd-timesyncd
