#!/usr/bin/env python
#
from arsoft.crypto.utils import check_mk_cert_check, check_mk_cert_inventory

def inventory_cups(checkname, info):

    ret = []
    if len(info) >= 1:
        data = { 'version_IPP':'', 'version_CUPS':'' }
        for line in info:
            if len(line) < 2:
                continue
            data[line[0]] = line[1]

        ret.append(('status', (data['version_CUPS'], data['version_IPP']))
        cert_checks = check_mk_cert_inventory(checkname, info, prefix=False, warn_time=30, crit_time=14)
        ret.extend(cert_checks)
    return ret

def check_cups(item, params, info):

    level   = 0 # 0:OK, 1:WARNING 2:CRITICAL, 3: UNKNOWN
    msg = None
    details = []
    perfdata = []
    data = { 'version_IPP':'', 'version_CUPS':'' }

    for line in info:
        if len(line) < 2:
            continue

        data[line[0]] = line[1]

    if check_name == 'status':
        (expected_cups_version, expected_ipp_version) = params

        if data['version_CUPS'] != expected_cups_version:
            if level < 1:
                level = 1
            details.append('CUPS version %s != %s' % (data['version_CUPS'], expected_cups_version))

        if data['version_IPP'] != expected_ipp_version:
            if level < 1:
                level = 1
            details.append('IPP version %s != %s' % (data['version_IPP'], expected_ipp_version))
        if level == 0:
            details.append('CUPS %s, IPP %s' % (data['version_CUPS'], data['version_IPP']))
    else:
        return check_mk_cert_check(item, params, info, prefix=False)

    # Construct a the status message.
    if level == 0:
        msg = "OK - %s" % (','.join(details))
    elif level == 1:
        msg = "WARN - %s" % (','.join(details))
    elif level == 2:
        msg = "CRIT - %s" % (','.join(details))
    return (level, msg, perfdata)

# declare the check to Check_MK.
check_info['cups'] = {
    'check_function':            check_cups,
    'inventory_function':        inventory_cups,
    'service_description':       'cups',
    'has_perfdata':              True,
}

