#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

def inventory_dmi_baseboard(checkname, info):
    if len(info) > 0 and info[0] == ['Base', 'Board', 'Information']:
        return [(None, None)]

def check_dmi_baseboard(item, param, info):
    if len(info) == 0 or info[0] != ['Base', 'Board', 'Information']:
        return (3, "Invalid information")
    data = {}
    for line in info:
        line = " ".join(line)
        if ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip()

    return (0, "%s %s, Version: %s, S/N %s" % (
                 data.get("Manufacturer", "Unknown"),
                 data.get("Product Name", "Unknown"),
                 data.get("Version", "Unknown"),
                 data.get("Serial Number", "Unknown"),
            ))



check_info["dmi_baseboard"] = {
    'check_function':          check_dmi_baseboard,
    'inventory_function':      inventory_dmi_baseboard,
    'service_description':     'DMI base board info',
}
