#!/usr/bin/env python
#
from arsoft.crypto.utils import check_mk_cert_check, check_mk_cert_inventory

def inventory_nginx_cert(checkname, info):
    return check_mk_cert_inventory(checkname, info, prefix=True, warn_time=30, crit_time=14)

def check_nginx_cert(item, params, info):
    return check_mk_cert_check(item, params, info, prefix=True)

# declare the check to Check_MK.
check_info['nginx_cert'] = {
    'check_function':            check_nginx_cert,
    'inventory_function':        inventory_nginx_cert,
    'service_description':       'nginx',
    'has_perfdata':              True,
}
