#!/usr/bin/env python
default_memory_usage_warn_threshold = None
default_memory_usage_crit_threshold = None

default_thread_count_warn_threshold = None
default_thread_count_crit_threshold = None

default_queuesize_warn_threshold = 2
default_queuesize_crit_threshold = 5

def inventory_puppetdb(checkname, info):

    ret = []
    if len(info) > 1:
        ret.append( ('daemon', (True) ) )
        ret.append( ('memory', (default_memory_usage_warn_threshold, default_memory_usage_crit_threshold) ) )
        ret.append( ('threads', (default_thread_count_warn_threshold, default_thread_count_crit_threshold) ) )
        ret.append( ('queue', (default_queuesize_warn_threshold, default_queuesize_crit_threshold) ) )
        ret.append( ('database', (default_queuesize_warn_threshold, default_queuesize_crit_threshold) ) )
    return ret

def check_puppetdb(item, params, info):

    level   = 0 # 0:OK, 1:WARNING 2:CRITICAL, 3: UNKNOWN
    msg = None
    details = []
    perfdata = []
    data = {}

    for line in info:
        # if we don't have any upgrades listed, the line list
        # will only contain one element, eg. "upgrades\n"
        if len(line) < 2:
            continue

        key = line[0]
        value = line[1]
        if '.' in value:
            try:
                value = float(value)
            except ValueError:
                value = 0.0
        elif key != 'version':
            value = saveint(value)
        data[key] = value

    if item == 'daemon':
        (must_be_running) = params
        if must_be_running:
            if data['running'] == 0 or data['pid'] == 0:
                if level < 2:
                    level = 2
                details.append('Not running')
        else:
            if data['running'] != 0 or data['pid'] != 0:
                if level < 2:
                    level = 2
                details.append('Running')

        if len(details) == 0:
            details.append('Version %s' % (data['version']))
    elif item == 'memory':
        if params:
            (memory_usage_warn_threshold, memory_usage_crit_threshold) = params
        else:
            (memory_usage_warn_threshold, memory_usage_crit_threshold) = (default_memory_usage_warn_threshold, default_memory_usage_crit_threshold)
            
        if data['running'] == 0 or data['pid'] == 0:
            level = 3
            details.append('puppetdb not running')
        else:
            perfdata.append( ('nonheapmemoryusage_max', data['memory_nonheapmemoryusage_max']) )
            perfdata.append( ('nonheapmemoryusage_init', data['memory_nonheapmemoryusage_init']) )
            perfdata.append( ('nonheapmemoryusage_used', data['memory_nonheapmemoryusage_used']) )
            perfdata.append( ('nonheapmemoryusage_committed', data['memory_nonheapmemoryusage_committed']) )

            perfdata.append( ('heapmemoryusage_max', data['memory_heapmemoryusage_max']) )
            perfdata.append( ('heapmemoryusage_init', data['memory_heapmemoryusage_init']) )
            perfdata.append( ('heapmemoryusage_used', data['memory_heapmemoryusage_used']) )
            perfdata.append( ('heapmemoryusage_committed', data['memory_heapmemoryusage_committed']) )

            heapmemoryusage_max = data['memory_heapmemoryusage_max']
            heapmemoryusage_init = data['memory_heapmemoryusage_init']
            heapmemoryusage_used = data['memory_heapmemoryusage_used']
            heapmemoryusage_committed = data['memory_heapmemoryusage_committed']

            nonheapmemoryusage_max = data['memory_nonheapmemoryusage_max']
            nonheapmemoryusage_init = data['memory_nonheapmemoryusage_init']
            nonheapmemoryusage_used = data['memory_nonheapmemoryusage_used']
            nonheapmemoryusage_committed = data['memory_nonheapmemoryusage_committed']

            if nonheapmemoryusage_max > 0:
                nonheapmemoryusage = float(nonheapmemoryusage_used) / float(nonheapmemoryusage_max)
            else:
                nonheapmemoryusage = None
            heapmemoryusage = float(heapmemoryusage_used) / float(heapmemoryusage_max)

            perfdata.append( ('nonheapmemoryusage', nonheapmemoryusage, memory_usage_warn_threshold, memory_usage_crit_threshold) )
            perfdata.append( ('heapmemoryusage', heapmemoryusage, memory_usage_warn_threshold, memory_usage_crit_threshold) )

            if memory_usage_crit_threshold is not None and memory_usage_warn_threshold is not None:
                if nonheapmemoryusage is not None:
                    if nonheapmemoryusage >= memory_usage_crit_threshold:
                        if level < 2:
                            level = 2
                        details.append('Non-Heap memory usage %i %%' % (int(nonheapmemoryusage * 100)))
                    elif nonheapmemoryusage >= memory_usage_warn_threshold:
                        if level < 1:
                            level = 1
                        details.append('Non-Heap memory usage %i %%' % (int(nonheapmemoryusage * 100)))
                if heapmemoryusage >= memory_usage_crit_threshold:
                    if level < 2:
                        level = 2
                    details.append('Heap memory usage %i %%' % (int(heapmemoryusage * 100)))
                elif heapmemoryusage >= memory_usage_warn_threshold:
                    if level < 1:
                        level = 1
                    details.append('Heap memory usage %i %%' % (int(heapmemoryusage * 100)))
            if len(details) == 0:
                if nonheapmemoryusage is not None:
                    details.append('Non-Heap %i %%' % (int(nonheapmemoryusage * 100)))
                details.append('Heap %i %%' % (int(heapmemoryusage * 100)))
    elif item == 'threads':
        if params:
            (thread_count_warn_threshold, thread_count_crit_threshold) = params
        else:
            (thread_count_warn_threshold, thread_count_crit_threshold) = (default_thread_count_warn_threshold, default_thread_count_crit_threshold)
        if data['running'] == 0 or data['pid'] == 0:
            level = 3
            details.append('puppetdb not running')
        else:
            
            threading_threadcount = data['threading_threadcount']
            threading_daemonthreadcount = data['threading_daemonthreadcount']
            
            perfdata.append( ('threadcount', threading_threadcount, thread_count_warn_threshold, thread_count_crit_threshold) )
            perfdata.append( ('daemonthreadcount', threading_daemonthreadcount, thread_count_warn_threshold, thread_count_crit_threshold) )
            
            if thread_count_warn_threshold is not None and thread_count_crit_threshold is not None:
                if threading_threadcount >= thread_count_crit_threshold:
                    if level < 2:
                        level = 2
                    details.append('High thread count %i' % (int(threading_threadcount)))
                elif threading_threadcount >= thread_count_warn_threshold:
                    if level < 1:
                        level = 1
                    details.append('High thread count %i' % (int(threading_threadcount)))
                if threading_daemonthreadcount >= thread_count_crit_threshold:
                    if level < 2:
                        level = 2
                    details.append('High daemon thread count %i' % (int(threading_daemonthreadcount)))
                elif threading_daemonthreadcount >= thread_count_warn_threshold:
                    if level < 1:
                        level = 1
                    details.append('High daemon thread count %i' % (int(threading_daemonthreadcount)))
            if len(details) == 0:
                details.append('%i threads, %i Daemon threads' % (int(threading_threadcount), int(threading_daemonthreadcount) ))
    elif item == 'queue':
        if params:
            (queuesize_warn_threshold, queuesize_crit_threshold) = params
        else:
            (queuesize_warn_threshold, queuesize_crit_threshold) = (default_queuesize_warn_threshold, default_queuesize_crit_threshold)
        if data['running'] == 0 or data['pid'] == 0:
            level = 3
            details.append('puppetdb not running')
        else:
            queuesize = data['mq_queuesize']
            averageenqueuetime = data['mq_averageenqueuetime']
            dispatchcount = data['mq_dispatchcount']

            perfdata.append( ('queuesize', queuesize, queuesize_warn_threshold, queuesize_crit_threshold) )
            perfdata.append( ('dispatchcount', dispatchcount) )
            perfdata.append( ('averageenqueuetime', averageenqueuetime) )

            if queuesize > queuesize_crit_threshold:
                if level < 2:
                    level = 2
                details.append('Queue size %i' % (queuesize))
            elif queuesize > queuesize_warn_threshold:
                if level < 1:
                    level = 1
                details.append('Queue size %i' % (queuesize))
            if len(details) == 0:
                details.append('Avg enqueue time %ss' % (averageenqueuetime))
                if queuesize == 0:
                    details.append('Queue is empty')
                else:
                    details.append('Queue size %i' % (queuesize))
    elif item == 'database':
        if params:
            (queuesize_warn_threshold, queuesize_crit_threshold) = params
        else:
            (queuesize_warn_threshold, queuesize_crit_threshold) = (default_queuesize_warn_threshold, default_queuesize_crit_threshold)
        if data['running'] == 0 or data['pid'] == 0:
            level = 3
            details.append('puppetdb not running')
        else:
            statementexecutetimeavg = data['db_statementexecutetimeavg']
            cachemiss = data['db_cachemiss']
            cachehits = data['db_cachehits']

            perfdata.append( ('db_cachehits', cachehits) )
            perfdata.append( ('db_cachemiss', cachemiss) )
            perfdata.append( ('db_avgquerytime', statementexecutetimeavg) )
            if len(details) == 0:
                details.append('Avg query time %ss, %i:%i Cache hits:misses' % (statementexecutetimeavg, cachehits, cachemiss))

    # Construct a the status message.
    if level == 0:
        msg = "OK - %s" % (','.join(details))
    elif level == 1:
        msg = "WARN - %s" % (','.join(details))
    elif level == 2:
        msg = "CRIT - %s" % (','.join(details))
    elif level == 3:
        msg = "UNKNOWN - %s" % (','.join(details))
    return (level, msg, perfdata)

# declare the check to Check_MK.
check_info['puppetdb'] = {
    'check_function':            check_puppetdb,
    'inventory_function':        inventory_puppetdb,
    'service_description':       'PuppetDB',
    'has_perfdata':              True,
}
