#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Check_MK APT Plugin - Check for upgradeable packages.
#
# Copyright 2010, Stefan Schlesinger <sts@ono.at>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from arsoft.timestamp import format_timedelta
from arsoft.check_mk import check_state

def inventory_rkhunter(checkname, info):

    ret = []
    if len(info) >= 1:
        ret.append( ('status', (48, 96) ) )
        ret.append( ('result', None) )

    return ret

def check_rkhunter(item, params, info):

    state = check_state()
    data = {
        'check_age':0,
        'num_infects':0,
        'num_criticals':0,
        'num_errors':0,
        'num_warnings':0,
        'num_infos':0,
        'num_file_properties_changed':0,
        'num_services_changed':0,
        'num_users_changed':0,
        'num_groups_changed':0,
        'num_downloads_failed':0,
        'num_missing_files':0,
        'changed_file_properties':[],
        'missing_files':[],
        'changed_services':[],
        'changed_users':[],
        'changed_groups':[],
        'downloads_failed':[],
        'warnings':[],
        'errors':[],
        'criticals':[],
        'infects':[],
        }

    for line in info:
        # if we don't have any upgrades listed, the line list
        # will only contain one element, eg. "upgrades\n"
        if len(line) < 2:
            continue

        # there are upgrades availiable, evaluate the importency.
        # secupgrades return CRITICAL, normal upgrades only WARNING.
        if line[0].startswith('num_') or line[0].startswith('check_'):
            value = saveint(line[1])
        else:
            value = line[1].split(",")
        data[line[0]] = value

    if item == 'status':
        (warn_time_hours, crit_time_hours) = params if params is not None else (48, 96)
        warn_time = (warn_time_hours * 3600)
        crit_time = (crit_time_hours * 3600)
        check_age = data['check_age']
        state.perfdata.append( ('check_age', int(check_age/3600), warn_time_hours, crit_time_hours ) )
        msg = 'last check %s ago' % format_timedelta(check_age)
        if check_age > crit_time:
            state.critical(msg)
        elif check_age > warn_time:
            state.warning(msg)
        else:
            state.ok(msg)
    else:
        if data['num_infects'] > 0:
            state.critical('%i infects %s' % (data['num_infects'], ','.join(data['infects']) ) )
        if data['num_criticals'] > 0:
            state.critical('%i criticals %s' % (data['num_criticals'], ','.join(data['criticals']) ) )
        if data['num_errors'] > 0:
            state.critical('%i errors %s' % (data['num_errors'], ','.join(data['errors']) ) )
        if data['num_warnings'] > 0:
            state.warning('%i warnings %s' % (data['num_warnings'], ','.join(data['warnings']) ) )

        if data['num_file_properties_changed'] > 0:
            state.warning('%i changed files %s' % (data['num_file_properties_changed'], ','.join(data['changed_file_properties']) ) )

        if data['num_missing_files'] > 0:
            state.warning('%i missing files %s' % (data['num_missing_files'], ','.join(data['missing_files']) ) )

        if data['num_services_changed'] > 0:
            state.warning('%i changed services %s' % (data['num_services_changed'], ','.join(data['changed_services']) ) )

        if data['num_users_changed'] > 0:
            state.warning('%i changed users %s' % (data['num_users_changed'], ','.join(data['changed_users']) ) )

        if data['num_groups_changed'] > 0:
            state.warning('%i changed groups %s' % (data['num_groups_changed'], ','.join(data['changed_groups']) ) )

        if data['num_downloads_failed'] > 0:
            state.warning('%i downloads failed %s' % (data['num_downloads_failed'], ','.join(data['downloads_failed']) ) )

        state.ok('No issues detected.')

        state.perfdata.append( ('num_infects', data['num_infects'], 1, 1) )
        state.perfdata.append( ('num_criticals', data['num_criticals'], 1, 1) )
        state.perfdata.append( ('num_errors', data['num_errors'], 1, 1) )
        state.perfdata.append( ('num_warnings', data['num_warnings'], 1, 0) )
        state.perfdata.append( ('num_infos', data['num_infos']) )
        state.perfdata.append( ('num_file_properties_changed', data['num_file_properties_changed'], 1, 0) )
        state.perfdata.append( ('num_missing_files', data['num_missing_files'], 1, 0) )
        state.perfdata.append( ('num_services_changed', data['num_services_changed'], 1, 0) )
        state.perfdata.append( ('num_users_changed', data['num_users_changed'], 1, 0) )
        state.perfdata.append( ('num_groups_changed', data['num_groups_changed'], 1, 0) )
        state.perfdata.append( ('num_downloads_failed', data['num_downloads_failed'], 1, 0) )

    return state.return_value

# declare the check to Check_MK.
check_info['rkhunter'] = {
    'check_function':            check_rkhunter,
    'inventory_function':        inventory_rkhunter,
    'service_description':       'rkhunter',
    'has_perfdata':              True,
}
