#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
from arsoft.check_mk import check_state

def inventory_systemd(checkname, info):
    return [ ('daemon', {} ) ]

def check_systemd(item, params, info):

    state = check_state()

    if item == 'daemon':
        version = info[0][1]
        state.ok('Version %s' % version)

    return state.return_value

# declare the check to Check_MK.
check_info['systemd'] = {
    'check_function':            check_systemd,
    'inventory_function':        inventory_systemd,
    'service_description':       'systemd',
    'has_perfdata':              False,
}
